### ISSUE TITLE
请问一下，如何爬取卫星图

### ISSUE THREAD

**Issue by QinYuGen** [JasonJe/offline-tileServer#1]
需要更改url或者是其他参数吗

**Comment by JasonJe** [comment]
需要改`URL`，高德的卫星地图的接口是这个`http://webst04.is.autonavi.com/appmaptile?style=6&x=843&y=388&z=10`。

常见的瓦片地址如下：

地图商 | 瓦片编码 | 图层 | 链接
-- | -- | -- | --
高德地图 | 谷歌XYZ | 道路 | http://webrd02.is.autonavi.com/appmaptile?lang=zh_cn&size=1&scale=1&style=8&x=105&y=48&z=7
高德地图 | 谷歌XYZ | 卫星 | http://webst04.is.autonavi.com/appmaptile?style=6&x=843&y=388&z=10
谷歌地图 | 谷歌XYZ | 道路 | http://mt2.google.cn/vt/lyrs=m&hl=zh-CN&gl=cn&x=105&y=48&z=7
谷歌地图 | 谷歌XYZ | 卫星 | http://mt2.google.cn/vt/lyrs=s&hl=zh-CN&gl=cn&x=105&y=48&z=7
谷歌地图 | 谷歌XYZ | 地形 | http://mt0.google.cn/vt/lyrs=t&hl=zh-CN&gl=cn&x=420&y=193&z=9
OpenStreetMap | 谷歌XYZ | 道路 | http://a.tile.openstreetmap.org/7/105/48.png
腾讯地图 | TMS | 道路 | http://rt1.map.gtimg.com/realtimerender?z=7&x=105&y=79&type=vector&style=0
Bing地图 | QuadTree | 道路 | http://r1.tiles.ditu.live.com/tiles/r1321001.png?g=100&mkt=zh-cn
百度地图 | 百度XYZ | 道路 | http://online4.map.bdimg.com/tile/?qt=tile&x=98&y=36&z=9&;styles=pl&scaler=1&udt=20170406
百度地图 | 百度XYZ | 交通 | http://its.map.baidu.com:8002/traffic/TrafficTileService?level=19&x=99052&y=20189&time=1373790856265&label=web2D&;v=017

**Comment by QinYuGen** [comment]
好的，感谢作者




------------------ 原始邮件 ------------------
发件人: "JasonJe"<notifications@github.com>; 
发送时间: 2019年5月5日(星期天) 下午5:00
收件人: "JasonJe/offline-tileServer"<offline-tileServer@noreply.github.com>; 
抄送: "ET+UFO"<1065113579@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [JasonJe/offline-tileServer] 请问一下，如何爬取卫星图 (#1)




需要改URL，高德的卫星地图的接口是这个http://webst04.is.autonavi.com/appmaptile?style=6&x=843&y=388&z=10。
 
常见的瓦片地址如下：
    地图商 瓦片编码 图层 链接 
    高德地图 谷歌XYZ 道路 http://webrd02.is.autonavi.com/appmaptile?lang=zh_cn&size=1&scale=1&style=8&x=105&y=48&z=7 
  高德地图 谷歌XYZ 卫星 http://webst04.is.autonavi.com/appmaptile?style=6&x=843&y=388&z=10 
  谷歌地图 谷歌XYZ 道路 http://mt2.google.cn/vt/lyrs=m&hl=zh-CN&gl=cn&x=105&y=48&z=7 
  谷歌地图 谷歌XYZ 卫星 http://mt2.google.cn/vt/lyrs=s&hl=zh-CN&gl=cn&x=105&y=48&z=7 
  谷歌地图 谷歌XYZ 地形 http://mt0.google.cn/vt/lyrs=t&hl=zh-CN&gl=cn&x=420&y=193&z=9 
  OpenStreetMap 谷歌XYZ 道路 http://a.tile.openstreetmap.org/7/105/48.png 
  腾讯地图 TMS 道路 http://rt1.map.gtimg.com/realtimerender?z=7&x=105&y=79&type=vector&style=0 
  Bing地图 QuadTree 道路 http://r1.tiles.ditu.live.com/tiles/r1321001.png?g=100&mkt=zh-cn 
  百度地图 百度XYZ 道路 http://online4.map.bdimg.com/tile/?qt=tile&x=98&y=36&z=9&;styles=pl&scaler=1&udt=20170406 
  百度地图 百度XYZ 交通 http://its.map.baidu.com:8002/traffic/TrafficTileService?level=19&x=99052&y=20189&time=1373790856265&label=web2D&;v=017
